[package]
name = "repro"
version = "0.1.0"
edition = "2024"
authors = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos-struct-table =  "0.15"
